version: "3"
services:
    mysql:
        container_name: trident_test_56_db
        restart: always
        image: mysql:8.3
        ports:
            - '33060:3306'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: trident_test
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - internal
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 2s
            retries: 10

    app:
        depends_on:
            mysql:
                condition: service_healthy
        container_name: trident_test_56_app
        build:
            context: .
        ports:
            - '8888:8000'
        networks:
            - internal
        command:
            - /bin/sh
            - -c
            - |
                php artisan migrate;
                php artisan serve --host 0.0.0.0;
networks:
    internal:
        driver: bridge
