openapi: 3.0.3
info:
  title: trident_test
  version: 1.0.0
  license:
    name: proprietary
  description: swagger-cli bundle app/docs/docs-root.yaml --outfile docs.yaml --type yaml --dereference
paths:
  /api/queues:
    get:
      tags:
        - Frontend API
      summary: 訂位首頁
      description: 訂位首頁
      operationId: api.queues.index
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                example:
                  seat: 2
                  current_number: 2
                  latest_number: 10
                  queue_count: 8
    post:
      summary: 個人線上訂位
      description: 個人線上訂位
      operationId: api.queues.store
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 姓名
                seat:
                  type: integer
                  description: 座位數
                phone:
                  type: string
                  description: 手機號碼
              required:
                - name
                - seat
                - phone
            example:
              name: test
              seat: 2
              phone: 0912345678
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  seat:
                    type: integer
                    description: 座位數
                  your_number:
                    type: integer
                    description: 你的號碼
                  current_number:
                    type: integer
                    description: 現在號碼
                  queue_count:
                    type: integer
                    description: 前面排隊人數
                example:
                  seat: 2
                  your_number: 30
                  current_number: 10
                  queue_count: 20
        '400':
          description: 爽約多次，請現場候位
  '/api/queues/{code}':
    get:
      summary: 個人訂位資訊
      description: 個人訂位資訊
      operationId: api.queues.show
      parameters:
        - in: path
          name: code
          schema:
            type: string
          required: true
          description: 混和加密編號
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  seat:
                    type: integer
                    description: 座位數
                  your_number:
                    type: integer
                    description: 你的號碼
                  current_number:
                    type: integer
                    description: 現在號碼
                  queue_count:
                    type: integer
                    description: 前面排隊人數
                example:
                  seat: 2
                  your_number: 30
                  current_number: 10
                  queue_count: 20
  /api/staff/queues:
    get:
      tags:
        - Staff API
      summary: 訂位後台管理
      description: 訂位後台管理
      operationId: api.staff.queues.index
      parameters:
        - in: query
          description: 日期搜尋
          name: date
          schema:
            type: string
            example: 2024-01-24T00:00:00.000Z
        - in: query
          description: 電話搜尋
          name: phone
          schema:
            type: string
            example: 0912123123
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    - created_at: 2024-01-24T12:00:00.000Z
                      seat: 2
                      queue_number: 321
                      check_in_at: null
                      check_out_at: null
                      no_show: false
                      booked_at: 2024-01-24T12:00:00.000Z
                    - created_at: 2024-01-24T12:00:00.000Z
                      seat: 4
                      queue_number: 123
                      check_in_at: 2024-01-24T12:00:00.000Z
                      check_out_at: 2024-01-24T12:10:00.000Z
                      no_show: false
                      booked_at: 2024-01-24T12:00:00.000Z
                  total: 2
    post:
      summary: 個人線上訂位
      description: 個人線上訂位
      operationId: api.staff.queues.store
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 姓名
                seat:
                  type: integer
                  description: 座位數
                phone:
                  type: string
                  description: 手機號碼
                date:
                  type: string
                  description: '日期, Y-m-d H:i:s, 必須是未來時間'
              required:
                - name
                - seat
                - phone
            example:
              name: test
              seat: 2
              phone: 0912345678
              date: 2024-01-24T15:00:00.000Z
      responses:
        '200':
          description: 直接回傳前台查詢網址
  /api/staff/queues/check-in:
    put:
      summary: 訂位報到
      description: 訂位報到
      operationId: api.staff.queues.check-in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: integer
                  description: 排隊編號
                table_id:
                  type: integer
                  description: 桌子編號
              required:
                - id
                - table_id
            example:
              id: 123
              table_id: 1
      responses:
        '200':
          description: ok
        '400':
          description: 座位數不足
  '/api/staff/queues/check-out/tables/{id}':
    put:
      summary: 離席
      description: 離席
      operationId: api.staff.queues.check-out
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: 桌子編號
      responses:
        '200':
          description: ok
  /api/staff/queues/report:
    get:
      tags:
        - Staff API
      summary: 訂位後台報表
      description: 訂位後台報表
      operationId: api.staff.queues.report
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  from_online:
                    type: integer
                    description: 線上訂位數
                  from_site:
                    type: integer
                    description: 現場訂位數
                  avg_wait_reports:
                    type: array
                    description: 平均等待時間報表
                    items:
                      type: object
                      properties:
                        started_hour:
                          type: integer
                          description: 時間區間（時）
                        avg_wait_time:
                          type: integer
                          description: 平均等待時間(秒)
                example:
                  from_online: 10
                  from_site: 2
                  avg_wait_reports:
                    - started_hour: 11
                      avg_wait_time: 10
                    - started_hour: 12
                      avg_wait_time: 15
                    - started_hour: 13
                      avg_wait_time: 12
  /api/staff/phones:
    get:
      tags:
        - Staff API
      summary: 使用者管理總覽
      description: 使用者管理總覽
      operationId: api.staff.phones.index
      parameters:
        - in: query
          description: '電話號碼, 多組'
          name: phones
          schema:
            type: array
            items:
              type: string
              example: 0912345678
        - in: query
          description: 是否黑名單
          name: is_blacklisted
          schema:
            type: boolean
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    - id: 1
                      phone: 0912345678
                      is_blacklisted: false
                    - id: 2
                      phone: 0912345679
                      is_blacklisted: true
                  total: 2
  /api/staff/phones/block-phones:
    put:
      summary: 電話加入黑名單
      description: 電話加入黑名單
      operationId: api.staff.phones.block-phones
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                    description: 資料庫的 phones.id
              required:
                - ids
            example:
              ids:
                - 1
                - 2
      responses:
        '200':
          description: ok
  /api/staff/phones/unblock-phones:
    put:
      summary: 電話解除黑名單
      description: 電話解除黑名單
      operationId: api.staff.phones.unblock-phones
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                    description: 資料庫的 phones.id
              required:
                - ids
            example:
              ids:
                - 1
                - 2
      responses:
        '200':
          description: ok
